---
swagger: '2.0'
info:
  description: 'This is a spec for zrachka_top api. See https://zhrachka_top.ukraine/about.html fro details.'
  version: 0.0.1
  title: Zhrachka Top Api
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: localhost
basePath: "/v1"
tags:
  - name: order
    description: Endpoints related to creating and viewing orders
schemes:
  - http
paths:
  /order:
    put:
      tags:
        - order
      summary: creates an order or returns the existing order if this order is already created
      operationId: createOrder
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderedFood
          in: body
          description: list of ordered food in json
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            "$ref": "#/definitions/ApiResponse"
definitions:
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
