# Generated by Django 4.1.5 on 2023-01-10 15:56

from django.db import migrations, models
import django.db.models.deletion
import receipt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("api_key", models.CharField(max_length=200)),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            (receipt.models.CheckType["KITCHEN"], "kitchen"),
                            (receipt.models.CheckType["CLIENT"], "client"),
                        ],
                        default=receipt.models.CheckType["KITCHEN"],
                        max_length=7,
                    ),
                ),
                ("point_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (receipt.models.CheckType["KITCHEN"], "kitchen"),
                            (receipt.models.CheckType["CLIENT"], "client"),
                        ],
                        max_length=7,
                    ),
                ),
                ("order", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (receipt.models.CheckStatus["NEW"], "new"),
                            (receipt.models.CheckStatus["RENDERED"], "rendered"),
                            (receipt.models.CheckStatus["PRINTED"], "printed"),
                        ],
                        max_length=8,
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="")),
                (
                    "printer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="receipt.printer",
                    ),
                ),
            ],
        ),
    ]
